---


config_dir: /etc/ansible-ovirt
engine_fqdn: rhev-engine.example.com
engine_username: admin@internal
admin_password: changeme
dc_name: Default

data_storage_type: nfs
data_storage_name: my_data_storage
data_storage_address: www.example.com
data_storage_path: /path/to/data

export_storage_type: nfs
export_storage_name: my_export_storage
export_storage_address: www.example.com
export_storage_path: /path/to/export

create_export_domain: false
